---


- name: install fish shell
  pacman:
    name: fish
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  
- name: Install oh-my-zsh-git and optional dependencies from AUR
  aur: name={{ item }} user={{ user.name }}
  with_items:
    - oh-my-zsh-git
    - oh-my-zsh-powerline-theme-git
  register: omzinstall
  until: omzinstall is success
  retries: 10
  delay: 2

- name: Install fish with completion and syntax
  pacman: name={{ item }} state=present
  with_items:
    - zsh
    - zsh-completions
    - zsh-syntax-highlighting
  register: zshinstall
  until: zshinstall is success
  retries: 10
  delay: 2
  notify: change shell

- name: Push customized agnoster theme
  copy:
    src: "custom_agnoster.zsh-theme"
    dest: "/usr/share/oh-my-zsh/themes/agnoster.zsh-theme"
  when: omzinstall is changed

- name: Ensure the cache folder with oh-my-zsh subfolder is present
  file:
    path: /home/{{ user.name }}/.cache/oh-my-zsh
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory
    mode: 0755
  when: omzinstall is changed

- name: Ensure the last working dir file for oh-my-zsh is present
  file:
    path: /home/{{ user.name }}/.cache/oh-my-zsh/last-working-dir
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: touch
  when: omzinstall is changed
